### ISSUE TITLE
Consider updating packaging and coordinates?

### ISSUE THREAD

**Issue by travisbrown** [typelevel/catbird#341]
As discussed [here](https://github.com/typelevel/general/issues/101), this repository is now in the Typelevel organization. It's not strictly necessary to move the project from `io.catbird` to `org.typelevel`, but I think it'd be a good idea. This would involve two changes:

* Change the publishing coordinates from `io.catbird` to `org.typelevel`. This is easy, simplifies publishing rights, and imposes a very small burden on users (just updating the dependency in their build config).
* Change the packaging from `io.catbird.*` to `org.typelevel.catbird.*`. This is more of a burden on users, but is a completely mechanical change.

We could technically just do the first but not the second, but I also think it'd be good to stay consistent, and I'd like to get rid of the io domain at some point (for [various reasons](https://gigaom.com/2014/06/30/the-dark-side-of-io-how-the-u-k-is-making-web-domain-profits-from-a-shady-cold-war-land-deal/)).

**Comment by felixbr** [comment]
I think the first point is obvious and while it might confuse a few users ([*ahem*](https://github.com/typelevel/log4cats/issues/404)), we can show a note about it in the readme for a while. 

Regarding the second point: What about using `catbird` as root package? All popular typelevel projects I've used ignore the reverse-domain package-naming convention and I personally prefer it to typing out `org.typelevel.` all the time.

`catbird` is a fairly unique name, so I don't expect name clashes to be a problem (`io` is actually what clashes often for me, e.g. when importing both `fs2._` and `io.circe._`).

**Comment by travisbrown** [comment]
@felixbr It's always bothered me that so much of the Scala ecosystem has gone that route, but I don't think I have good reasons for caring as much as I do, and I've been mostly successful at caring about it less. So my vote is a strong +1 for getting rid of `io` (which I want to do for Circe at some point, too) and a weak +1 for `org.typelevel.catbird`, but I'd be happy to go with `catbird` if that's what everyone else wants.

**Comment by felixbr** [comment]
I absolutely understand your frustration but at the same time it seems like this ship has sailed for Scala. I have a slight preference for the short names as long as they don't cause issues but `catbird` is mostly used for interop, so it's probably not imported in every file anyway. Both solutions are fine with me.

Maybe @dangerousben has a different opinion? 🙂

Anyway, more important to me is the timing. I'd like to merge the `cats-effect-3.x` stuff first but we can definitely do one release where we do all the naming changes at once, so users are only confused/annoyed once:

1. Rename the package `io.catbird` to either `catbird` or `org.typelevel.catbird`
2. Rename the artifact organization to `org.typelevel`
3. Rename the artifact for `cats-effect-2.x` to `catbird-effect2` and for `cats-effect-3.x` to `catbird-effect3` (`scalatestplus` uses dashes like `scalacheck-1-15` but `circe` uses no delimiter like `circe-jackson28`.)

If we document it properly in release notes, docs, and readme, it shouldn't be a problem.

**Comment by dangerousben** [comment]
> Maybe @dangerousben has a different opinion? 

No strong opinion, `catbird` seems pretty unlikely to clash with anything.
