### ISSUE TITLE
Release Cadence

### ISSUE THREAD

**Issue by bpholt** [typelevel/catbird#380]
There have been a handful of upstream releases from Twitter. Is there anything blocking a release for `21.8.0`?

Going forward, would it be possible to automatically release upon updates from Twitter, assuming everything passes in CI?

**Comment by bpholt** [comment]
Oh, from https://github.com/typelevel/catbird/pull/344#issuecomment-852253444 it looks like maybe Travis is the only person who can release at the moment. Would a PR converting over to sbt-ci-release be welcome?

**Comment by felixbr** [comment]
I'd personally prefer `sbt-ci-release`, so pushing a version tag will publish a release. Makes life easier and now that the project is hosted in `typelevel`, it makes sense to have a less centralized approach.

**Comment by travisbrown** [comment]
Apologies, just saw this. I can publish a release manually today, and I think we should go ahead and change the coordinates and packaging to `org.typelevel` as soon as possible so that others can publish. I'd also support switching to `sbt-ci-release`, although I don't have much experience with it and someone else would need to set it up.

**Comment by travisbrown** [comment]
Okay, [21.8.0](https://github.com/typelevel/catbird/releases/tag/v21.8.0) is on its way to Maven Central. I probably won't have time to make the packaging and coordinate changes this week, but would be more than happy to review that or an `sbt-ci-release` PR.

**Comment by bpholt** [comment]
Thanks @travisbrown! I'll try to put together a packaging / coordinate change PR later this week, unless someone beats me to it.

**Comment by bpholt** [comment]
Ok I obviously didn't get to this last week, but I haven't forgotten about it. Hopefully coming soon (again, unless someone else beats me to it).
