### ISSUE TITLE
Additional maintainer

### ISSUE THREAD

**Issue by rossabaker** [typelevel/catbird#434]
@bpholt has graciously stepped forward to continue maintaining Catbird.  It's always good to have a second maintainer, when either the person or the project gets busy.  Volunteers?

**Comment by milanvdm** [comment]
@rossabaker Could you add me as a maintainer? Im already part of Typelevel and currently using this project in the day-to-day job :)

**Comment by rossabaker** [comment]
Done, and thanks for stepping up!
