### ISSUE TITLE
Switch to Typelevel steward?

### ISSUE THREAD

**Issue by armanbilge** [typelevel/catbird#471]
I think Scala steward is updating this repo under its old location. We can remove it and add it to the Typelevel steward instead.

https://github.com/VirtusLab/scala-steward-repos/blob/695a916678fad5aa3eedc97796c67c5bfc114051/repos-github.md?plain=1#L1374

https://github.com/typelevel/steward/

**Comment by bpholt** [comment]
That sounds good to me!
